示範 Reactive Forms 的驗證方法
Date: 2020-03-14T08:14:30.902Z - Hash: 3ac64e4d7a19440737a3 - Time: 6136ms

ERROR in src/app/login2/login2.component.html:29:99 - error TS2345: Argument of type 'FormGroupDirective' is not assignable to parameter of type 'NgForm'.       Type 'FormGroupDirective' is missing the following properties from type 'NgForm': _directives, options, ngAfterViewInit, controls, and 2 more.

29                 <form class="user" [formGroup]="form" #templateForm="ngForm" (ngSubmit)="doSubmit(templateForm)">
                                                                                                     ~~~~~~~~~~~~

  src/app/login2/login2.component.ts:6:16
    6   templateUrl: './login2.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component Login2Component.

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
95% emitting index-html-webpack-plugin
    ERROR in src/app/login2/login2.component.ts:12:9 - error TS2304: Cannot find name 'FormGroupDirective'.

    12   form: FormGroupDirective;
               ~~~~~~~~~~~~~~~~~~